//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\amaur\Documents\Compiladores I\PruebasProyecto\Prueba3\antlrGrammar\tiny.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="tinyParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ItinyVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParse([NotNull] tinyParser.ParseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] tinyParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.lista_declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_declaracion([NotNull] tinyParser.Lista_declaracionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracion([NotNull] tinyParser.DeclaracionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.lista_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_id([NotNull] tinyParser.Lista_idContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.lista_sentencias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_sentencias([NotNull] tinyParser.Lista_sentenciasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentencia([NotNull] tinyParser.SentenciaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.seleccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeleccion([NotNull] tinyParser.SeleccionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.iteracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIteracion([NotNull] tinyParser.IteracionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.repeticion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeticion([NotNull] tinyParser.RepeticionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.sent_read"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSent_read([NotNull] tinyParser.Sent_readContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.sent_write"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSent_write([NotNull] tinyParser.Sent_writeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.bloque"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBloque([NotNull] tinyParser.BloqueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacion([NotNull] tinyParser.AsignacionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.b_expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitB_expresion([NotNull] tinyParser.B_expresionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.b_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitB_term([NotNull] tinyParser.B_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.not_factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot_factor([NotNull] tinyParser.Not_factorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.b_factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitB_factor([NotNull] tinyParser.B_factorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.relacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelacion([NotNull] tinyParser.RelacionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresion([NotNull] tinyParser.ExpresionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.termino"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermino([NotNull] tinyParser.TerminoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.signoFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignoFactor([NotNull] tinyParser.SignoFactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] tinyParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.sumaOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSumaOp([NotNull] tinyParser.SumaOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tinyParser.multOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultOp([NotNull] tinyParser.MultOpContext context);
}
